/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package logger.java;

import org.junit.jupiter.api.Test;

import logger.bfmtech.BfmLogger;
import logger.bfmtech.common.AccessLog;
import logger.bfmtech.common.Logger;
import logger.bfmtech.common.LoggerMethod;

class AppTest {
    @Test
    void appHasAGreeting() {
        try {
            /**
             * 日志的传送方式
             * LoggerMethod.Console 打印到输出台
             * LoggerMethod.File 保存到本地
             * LoggerMethod.Http 上传到阿里云日志平台
             */
            Logger myLogger = BfmLogger.initialize("appName", LoggerMethod.Console);
            myLogger.Debug("测试下Debug");
            myLogger.Info("测试下Info");
            myLogger.Warn("测试下Warn");
            myLogger.Access(new AccessLog("测试下Access", 1, System.currentTimeMillis(),
                    System.currentTimeMillis() + 24 * 60 * 60, "referer", "httphost", "interfac", "reqquery", "reqbody",
                    "resbody", "clientip", "useragent", "headers"));
            myLogger.Error(new Exception("测试下Error"));
            // log 关闭方法 模式是 LoggerMethod.Http 时候必须调用 否则会有数据丢失的风险
            myLogger.Close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
